"""Deterministic and safe Ren'Py rendering from validated scene plans."""

from __future__ import annotations

import json
import re
import unicodedata
from pathlib import PurePosixPath

from core.schemas import SceneBeat, ScenePlan, StateValue, VNProject


def sanitize_identifier(value: str, prefix: str = "item") -> str:
    """Convert arbitrary text to a valid, non-reserved Ren'Py identifier."""
    normalized = unicodedata.normalize("NFKD", value)
    ascii_value = normalized.encode("ascii", "ignore").decode("ascii")
    identifier = re.sub(r"[^A-Za-z0-9_]+", "_", ascii_value).strip("_").lower()
    if not identifier or not identifier[0].isalpha():
        identifier = f"{prefix}_{identifier}".rstrip("_")
    if identifier in {
        "default",
        "define",
        "hide",
        "image",
        "init",
        "jump",
        "label",
        "menu",
        "play",
        "python",
        "return",
        "scene",
        "screen",
        "show",
        "transform",
    }:
        identifier = f"{prefix}_{identifier}"
    return identifier[:80]


def safe_filename(value: str, fallback: str = "scene") -> str:
    """Return a cross-platform filename stem with no path components."""
    return sanitize_identifier(value, fallback)


def escape_text(value: str) -> str:
    """Escape creator text for a Ren'Py quoted string.

    Braces and brackets are doubled so input cannot unexpectedly invoke text
    tags or interpolation.
    """
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("{", "{{")
        .replace("[", "[[")
    )


def _literal(value: StateValue) -> str:
    """Render a typed state value without allowing executable expressions."""
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, int | float):
        return repr(value)
    return json.dumps(value, ensure_ascii=False)


def _initial_value(value: StateValue) -> StateValue:
    """Return a neutral initial value before any player choice is made."""
    if isinstance(value, bool):
        return False
    if isinstance(value, int):
        return 0
    if isinstance(value, float):
        return 0.0
    return ""


def _asset_path(asset_type: str, name: str, file_path: str = "") -> str:
    """Resolve a project-relative asset path for declarations and playback."""
    if file_path:
        normalized = file_path.replace("\\", "/")
        path = PurePosixPath(normalized)
        if not path.is_absolute() and ".." not in path.parts:
            return normalized
    if asset_type in {"background", "character"}:
        return f"images/{name}.svg"
    return f"audio/{name}.wav"


def _render_beat(beat: SceneBeat, assets: dict[str, tuple[str, str]]) -> list[str]:
    """Render a single validated beat."""
    transition = "" if beat.transition == "none" else f" with {beat.transition}"
    if beat.kind == "narration":
        return [f'    "{escape_text(beat.text)}"']
    if beat.kind == "dialogue":
        speaker = beat.speaker or "narrator"
        return [f'    {speaker} "{escape_text(beat.text)}"']
    if beat.kind == "scene" and beat.asset_id:
        return [f"    scene {beat.asset_id}{transition}"]
    if beat.kind == "show" and beat.asset_id:
        expression = f" {beat.expression}" if beat.expression else ""
        return [f"    show {beat.asset_id}{expression}{transition}"]
    if beat.kind == "hide" and beat.asset_id:
        return [f"    hide {beat.asset_id}{transition}"]
    if beat.kind in {"music", "sound"} and beat.asset_id:
        asset_type, path = assets.get(beat.asset_id, (beat.kind, ""))
        channel = "music" if asset_type == "music" else "sound"
        return [f'    play {channel} "{escape_text(path)}"'] if path else []
    if beat.kind == "pause":
        return [f"    pause {beat.duration or 0.5:g}"]
    return []


def render_scene(plan: ScenePlan, include_definitions: bool = True) -> str:
    """Render one scene as deterministic Ren'Py source."""
    lines = ["# Generated by VNForge. Safe to edit after export.", ""]
    assets = {
        asset.name: (
            asset.cue_type,
            _asset_path(asset.cue_type, asset.name, asset.file_path),
        )
        for asset in plan.asset_cues
    }
    if include_definitions:
        speakers = {
            beat.speaker: beat.speaker_name or beat.speaker.replace("_", " ").title()
            for beat in plan.beats
            if beat.kind == "dialogue" and beat.speaker
        }
        for speaker, display_name in sorted(speakers.items()):
            lines.append(f'define {speaker} = Character("{escape_text(display_name)}")')
        variables = {
            change.name: _initial_value(change.value)
            for choice in plan.choices
            for change in choice.state_changes
        }
        for name, value in sorted(variables.items()):
            lines.append(f"default {name} = {_literal(value)}")
        for asset in sorted(plan.asset_cues, key=lambda item: item.name):
            if asset.cue_type in {"background", "character"}:
                path = _asset_path(asset.cue_type, asset.name, asset.file_path)
                lines.append(f'image {asset.name} = "{escape_text(path)}"')
                for variant in asset.variants:
                    lines.append(f'image {asset.name} {variant} = "{escape_text(path)}"')
        if speakers or variables or plan.asset_cues:
            lines.append("")

    lines.append(f"label scene_{plan.scene_id}:")
    for beat in plan.beats:
        lines.extend(_render_beat(beat, assets))
    if not plan.choices:
        lines.extend(["", "    return"])
        return "\n".join(lines).rstrip() + "\n"

    lines.extend(["", "    menu:"])
    for choice in plan.choices:
        lines.append(f'        "{escape_text(choice.choice_text)}":')
        for change in choice.state_changes:
            lines.append(f"            $ {change.name} = {_literal(change.value)}")
        target = f"scene_{choice.target_scene_id}" if choice.target_scene_id else choice.route_label
        lines.append(f"            jump {target}")

    for choice in plan.choices:
        if choice.target_scene_id:
            continue
        lines.extend(
            [
                "",
                f"label {choice.route_label}:",
                f'    "{escape_text(choice.consequence)}"',
                "    return",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def render_project(project: VNProject) -> str:
    """Render all project scenes into one self-contained script."""
    if not project.scenes:
        return 'label start:\n    "Add a scene in VNForge first."\n    return\n'

    combined_assets = {}
    speakers = {}
    variables = {}
    for project_scene in project.scenes:
        plan = project_scene.plan
        combined_assets.update({asset.name: asset for asset in plan.asset_cues})
        speakers.update(
            {
                beat.speaker: beat.speaker_name or beat.speaker.replace("_", " ").title()
                for beat in plan.beats
                if beat.kind == "dialogue" and beat.speaker
            }
        )
        variables.update(
            {
                change.name: _initial_value(change.value)
                for choice in plan.choices
                for change in choice.state_changes
            }
        )

    lines = ["# Generated by VNForge.", ""]
    for speaker, display_name in sorted(speakers.items()):
        lines.append(f'define {speaker} = Character("{escape_text(display_name)}")')
    for name, value in sorted(variables.items()):
        lines.append(f"default {name} = {_literal(value)}")
    for asset in sorted(combined_assets.values(), key=lambda item: item.name):
        if asset.cue_type in {"background", "character"}:
            path = _asset_path(asset.cue_type, asset.name, asset.file_path)
            lines.append(f'image {asset.name} = "{escape_text(path)}"')
            for variant in asset.variants:
                lines.append(f'image {asset.name} {variant} = "{escape_text(path)}"')
    first_scene_id = project.scenes[0].plan.scene_id
    lines.extend(["", "label start:", f"    jump scene_{first_scene_id}", ""])
    for project_scene in project.scenes:
        namespaced_plan = project_scene.plan.model_copy(deep=True)
        for choice in namespaced_plan.choices:
            if not choice.target_scene_id:
                choice.route_label = sanitize_identifier(
                    f"{namespaced_plan.scene_id}_{choice.route_label}", "route"
                )
        rendered = render_scene(namespaced_plan, include_definitions=False)
        body = rendered.split("\n", 2)[-1]
        lines.extend([body.rstrip(), ""])
    return "\n".join(lines).rstrip() + "\n"
